# This is the BeamMP-Server config file.
# Help & Documentation: `https://wiki.beammp.com/en/home/server-maintenance`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://beammp.com/k/dashboard` on the left under "Keys"

[General]
Name = "Beam   MP Server"
Port = 30814
AuthKey = ""
LogChat = true
Debug = false
Private = true
MaxCars = 1
MaxPlayers = 8
Map = "/levels/PikesPeakDirt/info.json"
Description = "This is a    test"
ResourceFolder = "Resources"

[Misc]
ImScaredOfUpdates = true
SendErrorsShowMessage = false
SendErrors = false

[HTTP]
HTTPServerIP = "127.3.0.1"
SSLKeyPath = ".\\rockbouncer_suspension_R.pem"
SSLCertPath = ".\\rockbouncer_suspension_R.pem"
HTTPServerPort = "80804"
UseSSL = true
HTTPServerEnabled = true
